sudo: enabled
dist: bionic
language: cpp
os: linux

branches:
  only:
    - master

env:
  global:
    - LSAN_OPTIONS=suppressions=$HOME/supress.txt
    - ASAN_OPTIONS=symbolize=1,abort_on_error=1,detect_leaks=1

addons:
  apt:
    packages:
      - graphviz
      - gdb

cache:
  directories:
  - /opt/boost_1_71_0
  - build-dbg/third_party  # Relative to $TRAVIS_BUILD_DIR
  - $HOME/doxygen/doxygen-1.8.15/bin
  ccache: true

before_cache:
  - ls $TRAVIS_BUILD_DIR/build-dbg/third_party
  - doxygen -v

before_install:
  # Fix for Ubuntu Xenial apt-daily.service triggering
  # https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
  - |
    sudo ln -sf /usr/local/clang-7.0.0/bin/clang++ /usr/bin/clang++-7
    sudo systemctl stop apt-daily.timer
    sudo systemctl stop apt-daily.service &&
    sudo systemctl kill --kill-who=all apt-daily.service
    while (pgrep -cf apt.systemd.daily > /dev/null); do
      sleep 1
    done
  - sudo apt update -qq
  - eval "${MATRIX_EVAL}"
  # Travis has an OLD doxygen build, so we fetch a recent one
  - export DOXY_BINPATH=$HOME/doxygen/doxygen-1.8.15/bin
  - |
    if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      mkdir -p ~/doxygen && cd ~/doxygen
      wget https://netix.dl.sourceforge.net/project/doxygen/rel-1.8.15/doxygen-1.8.15.linux.bin.tar.gz
      tar xzf doxygen-1.8.15.linux.bin.tar.gz
      cd -
    fi
  - export PATH=$PATH:$DOXY_BINPATH

install:
  - sudo $TRAVIS_BUILD_DIR/install-dependencies.sh

before_script:
  - printf "leak:MallocExtension\nleak:event_base_once" > $HOME/supress.txt
  - cmake --version
  - env
  - ls build-dbg/third_party || true
  - ls -l /opt/
  - ls -l /usr/lib/ccache
  - ls -l /usr/bin/

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir testresults && mkdir -p build-dbg && cd build-dbg
  - cmake -L -DCMAKE_BUILD_TYPE=Debug -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ..
  - ninja -j4 base array_test dynasm_project libosmium_project
  - travis_wait ninja protobuf_project
  - tests_list=$(ctest -L CI -N | grep "Test.*#" | cut -f2 -d:| sort)
  - ninja -j4 $tests_list asio_fibers gsod_group -k 10
  - echo $tests_list |  xargs -n1 -t ../scripts/run_test.sh -l ../testresults -t 25 --name

after_failure:
  - pwd
  - find third_party/src/ -regex ".*\(err\|out\).log" | xargs -n 3 -t cat
  - find ../testresults | xargs -n 3 -t cat

jobs:
  fast_finish: true
  include:
  - stage: Build
    env: MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    compiler: clang
  -
    env: MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    compiler: clang
    addons:
        apt:
          packages:
            - clang-8
  - # Stage Build
    env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    compiler: gcc
  - # Stage Build
    env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    compiler: gcc
    addons:
        apt:
          packages:
          - g++-8

  - stage: deploy
    script: |
      if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
        mkdir -p build-dbg && cd build-dbg
        cmake -L -DCMAKE_BUILD_TYPE=Debug -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ..
        ninja doc
      fi
    deploy:
      provider: pages
      skip_cleanup: true
      local_dir: build-dbg/doc/html
      github_token: $GH_REPO_TOKEN
      on:
        branch: master


